apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitang-orderbook-liveorderbook-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitang-orderbook-liveorderbook-worker
  template:
    metadata:
      labels:
        app: pitang-orderbook-liveorderbook-worker
    spec:
      containers:
      - name: pitang-orderbook-liveorderbook-worker
        image: pitang-orderbook-liveorderbook-worker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pitang-orderbook-liveorderbook-worker-service
spec:
  type: NodePort
  selector:
    app: pitang-orderbook-liveorderbook-worker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
